

paths:
  data_path: "data/raw/ml-1m/ratings.dat"
  model_save_path: "matrix_factorization_model.pth"

hyperparameters:
  k: 20
  learning_rate: 0.001
  regularization: 0.02
  epochs: 100
  top_k: 10
  patience: 10